number=CA_CODIGO
short_description=TE_BREVE_DESCRIPCION
state=TE_ESTADO
start_date=FE_INICIO_PLANIFICADA
end_date=FE_FIN_PLANIFICADA
assigned_to=TE_ASIGNADO_A
opened_at=FE_ABIERTO
opened_by=TE_ABIERTO_POR
sys_mod_count=NU_ACTUALIZACIONES
sys_updated_on=FE_ACTUALIZADO
sys_updated_by=CA_ACTUALIZADO_POR
cmdb_ci=TE_CI_AFECTADO
closed_at=FE_CERRADO
closed_by=TE_CERRADO_POR
comments_and_work_notes=TE_COMENTARIOS_NOTAS
conflict_last_run=FE_CONFLICTO_ULT_EJECUCION
sys_created_on=FE_CREADO
sys_created_by=CA_CREADO_POR
close_code=TE_CODIGO_CIERRE
u_department=TE_DEPARTAMENTO
description=TE_DESCRIPCION
calendar_duration=NU_DURACION
business_duration=NU_DURACION_NEGOCIO
company=TE_EMPRESA
phase_state=TE_ESTADO_FASE
sys_tags=TE_ETIQUETAS
approval_set=FE_CREACION_APROBACION
work_end=FE_FINALIZACION_REAL
work_start=FE_INICIO_REAL
review_date=FE_REVISION
due_date=FE_VENCIMIENTO
sla_due=FE_VENCIMIENTO_SLA
correlation_id=TE_ID_CORRELACION
impact=TE_IMPACTO
expected_start=FE_INICIO_ESPERADO
u_no_ci=TE_NO_EXISTE_CI
close_notes=TE_NOTAS_CIERRE
work_notes=TE_NOTAS_TRABAJO
reassignment_count=NU_REASIGNACION
task_effective_number=CA_NUMERO_EFECTIVO
comments=TE_OBSERVACIONES_ADICIONALES
review_comments=TE_OBSERVACIONES_REVISION
order=TE_ORDEN
parent.parent=TE_PRINCIPAL
priority=TE_PRIORIDAD
risk=TE_RIESGO
business_service=TE_SERVICIO
requested_by=TE_SOLICITADO_POR
requested_by_date=TE_SOLICITADO_POR_FECHA
u_subcategory=TE_SUBCATEGORIA
time_worked=NU_TIEMPO_TRABAJADO
urgency=TE_URGENCIA
activity_due=FE_VENCIMIENTO_ACTIVIDAD
scope=TE_AMBITO