inc_number=CA_CODIGO
inc_category=CA_CATEGORIA
taskslatable_sla=CA_DEFINICION_SLA
taskslatable_stage=CA_ETAPA
inc_opened_at=FE_ABIERTO
inc_opened_by=TE_ABIERTO_POR
inc_reopened_time=FE_ABIERTO_POR_ULTIMA_VEZ
inc_reopened_by=TE_ABIERTO_POR_ULTIMA_VEZ_POR
inc_actions_taken=TE_ACCIONES_TOMADAS
inc_active=FL_ACTIVO
taskslatable_active=FL_ACTIVO_2
inc_sys_mod_count=NU_ACTUALIZACIONES
taskslatable_sys_mod_count=NU_ACTUALIZACIONES_2
inc_sys_updated_on=FE_ACTUALIZADO
taskslatable_sys_updated_on=FE_ACTUALIZADO_2
inc_sys_updated_by=TE_ACTUALIZADO_POR
taskslatable_sys_updated_by=TE_ACTUALIZADO_POR_2
inc_approval=TE_APROBACION
inc_assigned_to=TE_ASIGNADO_A
inc_short_description=TE_BREVE_DESCRIPCION
inc_cmdb_ci=TE_CI_AFECTADO
inc_contact_type=TE_CANAL
inc_cause=TE_CAUSA_PROBABLE
inc_caused_by=CA_CAUSADA_POR_EL_CAMBIO
inc_closed_at=FE_CERRADO
inc_closed_by=TE_CERRADO_POR
inc_comments_and_work_notes=TE_COMENTARIOS_NOTAS
inc_knowledge=FL_CONOCIMIENTO
inc_u_contact=TE_CONTACTO
inc_contract=TE_CONTRATO
inc_sys_created_on=FE_CREADO
taskslatable_sys_created_on=FE_CREADO_SLA
inc_sys_created_by=TE_CREADO_POR
taskslatable_sys_created_by=TE_CREADO_POR_2
inc_close_code=CA_CODIGO_RESOLUCION
inc_u_department=TE_DEPARTAMENTO
inc_description=TE_DESCRIPCION
inc_upon_approval=TE_DESPUES_APROBACION
inc_upon_reject=TE_DESPUES_RECHAZO
inc_sys_domain=TE_DOMINIO
inc_calendar_duration=NU_DURACION
taskslatable_pause_duration=NU_DURACION_PAUSA
taskslatable_business_pause_duration=NU_DURACION_PAUSA_NEGOCIO
inc_business_duration=NU_DURACION_NEGOCIO
taskslatable_business_duration=NU_DURACION_NEGOCIO_2
taskslatable_duration=NU_DURACION_REAL
inc_company=TE_EMPRESA
inc_user_input=TE_ENTRADA_USUARIO
inc_u_wrong_assignment=FL_ERROR_ASIGNACION
inc_escalation=TE_ESCALADO
inc_state=TE_ESTADO
inc_incident_state=TE_ESTADO_INCIDENTE
inc_major_incident_state=TE_ESTADO_INC_SIGNIFICATIVA
inc_sys_tags=TE_ETIQUETAS
inc_approval_set=FE_CREACION_APROBACION
inc_due_date=FE_VENCIMIENTO
inc_sla_due=FE_VENCIMIENTO_SLA
inc_work_end=FE_FINALIZACION_REAL
inc_severity=CA_GRAVEDAD
inc_u_previous_assignment_group=TE_GRUPO_ASIGNADO_PREVIO
inc_assignment_group=TE_GRUPO_ASIGNACION
taskslatable_has_breached=FL_INFRACCION
inc_approval_history=TE_HISTORIAL
taskslatable_end_time=FE_HORA_FIN
taskslatable_planned_end_time=FE_HORA_INFRACCION
taskslatable_start_time=FE_HORA_INICIO
inc_correlation_id=TE_ID_CORRELACION
inc_sys_id=TE_ID_SISTEMA
taskslatable_sys_id=TE_ID_SISTEMA_2
inc_impact=CA_IMPACTO
inc_business_impact=TE_IMPACTO_NEGOCIO
inc_u_security_incident=TE_INCIDENTE_SEGURIDAD
inc_parent_incident=TE_INCIDENTE_PRINCIPAL
inc_child_incidents=NU_INCIDENTES_SECUNDARIOS
inc_expected_start=FE_INICIO_ESPERADO
inc_work_start=FE_INICIO_REAL
inc_additional_assignee_list=TE_ASIGNADOS_ADICIONALES
inc_group_list=TE_LISTA_GRUPOS
inc_work_notes_list=TE_LISTA_NOTAS_TRABAJO
inc_watch_list=TE_LISTA_SEGUIMIENTO
inc_timeline=TE_LINEA_DE_TIEMPO
inc_route_reason=TE_MOTIVO_TRANSFERENCIA
inc_hold_reason=TE_MOTIVO_ESPERA
inc_close_notes=TE_NOTAS_RESOLUCION
inc_work_notes=TE_NOTAS_TRABAJO
inc_notify=TE_NOTIFICAR
inc_reassignment_count=NU_NUMERO_REASIGNACION
inc_task_effective_number=CA_NUMERO_EFECTIVO
inc_comments=TE_OBSERVACIONES_ADICIONALES
inc_service_offering=TE_OFERTA_SERVICIO
inc_u_option=TE_OPCION
inc_order=NU_ORDEN
inc_origin_id=TE_ORIGEN
inc_delivery_plan=TE_PLAN_ENTREGA
taskslatable_business_percentage=NU_PCT_NEGOCIO_TRANSCURRIDO
taskslatable_percentage=NU_PCT_REAL_TRANSCURRIDO
inc_parent=TE_PRINCIPAL
inc_priority=CA_PRIORIDAD
inc_problem_id=TE_PROBLEMA
taskslatable_schedule=TE_PROGRAMA
inc_promoted_on=TE_PROMOCIONADO
inc_promoted_by=TE_PROMOCIONADO_POR
inc_proposed_on=TE_PROPUESTO
inc_proposed_by=TE_PROPUESTO_POR
inc_u_vendor=TE_PROVEEDOR
inc_reopen_count=NU_REAPERTURAS
inc_u_claim_count=NU_RECLAMACIONES
inc_u_claimed=FL_RECLAMADA
inc_u_claimed_by=TE_RECLAMADA_POR
inc_trigger_rule=TE_REGLA_DESENCADENAMIENTO
inc_u_pending_request=CA_REQUEST
inc_resolved_at=FE_RESUELTO
inc_resolved_by=TE_RESUELTO_POR
inc_lessons_learned=TE_RESULTADOS
inc_overview=TE_RESUMEN
inc_sys_domain_path=TE_RUTA_DOMINIO
taskslatable_u_assignment_group=TE_SLA_GRUPO_ASIGNACION
inc_made_sla=TE_SLA_CREADO
inc_follow_up=TE_SEGUIMIENTO
inc_business_service=TE_SERVICIO
inc_caller_id=TE_SOLICITANTE
inc_universal_request=TE_SOLICITUD_UNIVERSAL
inc_rfc=TE_SOLUCIONADA_CON_CAMBIO
inc_subcategory=TE_SUBCATEGORIA
inc_origin_table=TE_TABLA_ORIGEN
taskslatable_task=CA_TAREA
inc_delivery_task=TE_TAREA_ENTREGA
taskslatable_business_time_left=NU_TIEMPO_NEGOCIO_RESTANTE
taskslatable_pause_time=FE_TIEMPO_PAUSA
inc_calendar_stc=NU_TIEMPO_RESOLUCION
inc_business_stc=NU_TIEMPO_RESOLUCION_EMPRESA
taskslatable_original_breach_time=FE_TIEMPO_ORIGINAL_INCUMPLIDO
taskslatable_time_left=NU_TIEMPO_RESTANTE_REAL
inc_time_worked=NU_TIEMPO_TRABAJADO
inc_u_type=TE_TIPO_INCIDENCIA
inc_sys_class_name=TE_TIPO_TAREA
inc_location=TE_UBICACION
inc_urgency=CA_URGENCIA
inc_activity_due=FE_VENCIMIENTO_ACTIVIDAD
inc_correlation_display=TE_VISUALIZACION_CORRELACION
taskslatable_timezone=TE_ZONA_HORARIA
taskslatable_sys_tags=TE_SYS_TAGS