number=CA_CODIGO
cat_item=TE_ELEMENTO
stage=TE_ETAPA
request=CA_SOLICITUD
requested_for=TE_SOLICITADO
request.opened_by=TE_ABIERTO_POR
due_date=FE_VENCIMIENTO
quantity=NU_CANTIDAD
assignment_group=TE_GRUPO_ASIGNACION
opened_at=FE_ABIERTO
u_accept_reopen=NU_ACEPTAR_REAPERTURA
sys_mod_count=NU_ACTUALIZACIONES
sys_updated_on=FE_ACTUALIZADO
sys_updated_by=CA_ACTUALIZADO_POR
assigned_to=TE_ASIGNADO_A
cmdb_ci=TE_CI_AFECTADO
closed_at=FE_CERRADO
closed_by=TE_CERRADO_POR
comments_and_work_notes=TE_COMENTARIOS_NOTAS
sys_created_on=FE_CREADO
sys_created_by=CA_CREADO_POR
u_department=TE_DEPARTAMENTO
description=TE_DESCRIPCION
calendar_duration=NU_DURACION
business_duration=NU_DURACION_NEGOCIO
configuration_item=TE_ELEMENTO_CONFIGURACION
estimated_delivery=FE_ENTREGA_ESTIMADA
escalation=TE_ESCALADO
state=TE_ESTADO
sys_tags=TE_ETIQUETAS
work_end=FE_FINALIZACION_REAL
u_previous_assignment_group=TE_GRUPO_ASIGNADO_PREVIO
impact=CA_IMPACTO
expected_start=FE_INICIO_ESPERADO
work_start=FE_INICIO_REAL
close_notes=TE_NOTAS_CIERRE
work_notes=TE_NOTAS_TRABAJO
reassignment_count=NU_REASIGNACION
task_effective_number=CA_NUMERO_EFECTIVO
comments=TE_OBSERVACIONES_ADICIONALES
u_option=TE_OPCION
order=TE_ORDEN
priority=TE_PRIORIDAD
u_reopen_count=NU_REOPEN_COUNT
u_reopened_date=FE_REOPENED_DATE
time_worked=NU_TIEMPO_TRABAJADO
urgency=TE_URGENCIA
variables.a70ee33e47e786907b37945e036d4354=FE_PLAN_ENTREGA_EJECUCION
variables.18d673ba47eb86907b37945e036d43d2=NU_HORAS_EST_TOT_EJECUCION
variables.19477bfa47eb86907b37945e036d4357=NU_HORAS_TOT_EJECUCION
variables.d141afcc477a96907b37945e036d43cc=TE_ESTIMACION_VALIDADA_REPAROS
variables.2b4c7ed547da12107b37945e036d430d=FE_PLAN_ENTREGA_ANALISIS
variables.4c71a780477a96907b37945e036d4358=FE_PLAN_INICIO_ANALISIS
variables.988cb6d547da12107b37945e036d4358=NU_HORAS_EST_TOT_ANALISIS
variables.3c9cf2d547da12107b37945e036d4395=NU_HORAS_REALES_TOT_ANALISIS
variables.c8acb6d547da12107b37945e036d43b0=TE_TRABAJO_EQUIPO_FACTORIA