sct_number=CA_CODIGO
sct_short_description=TE_BREVE_DESCRIPCION
taskslatable_stage=TE_ETAPA
sct_opened_at=FE_ABIERTO
sct_opened_by=TE_ABIERTO_POR
sct_sys_mod_count=NU_ACTUALIZACIONES
taskslatable_sys_mod_count=NU_ACTUALIZACIONES_2
sct_sys_updated_on=FE_ACTUALIZADO
taskslatable_sys_updated_on=FE_ACTUALIZADO_2
taskslatable_sys_updated_by=CA_ACTUALIZADO_POR
sct_assigned_to=TE_ASIGNADO_A
sct_cmdb_ci=TE_CI_AFECTADO
sct_closed_at=FE_CERRADO
sct_closed_by=TE_CERRADO_POR
sct_comments_and_work_notes=TE_COMENTARIOS_NOTAS
sct_sys_created_on=FE_CREADO_TAREA
taskslatable_sys_created_on=FE_CREADO_SLA
taskslatable_sys_created_by=CA_CREADO_POR
sct_description=TE_DESCRIPCION
sct_calendar_duration=NU_DURACION
taskslatable_pause_duration=NU_DURACION_PAUSA
taskslatable_business_pause_duration=NU_DURACION_PAUSA_NEGOCIO
sct_business_duration=NU_DURACION_NEGOCIO
taskslatable_business_duration=NU_DURACION_NEGOCIO_2
taskslatable_duration=NU_DURACION_REAL
sct_request_item=TE_ELEMENTO_SOLICITUD
sct_state=TE_ESTADO
sct_sys_tags=TE_ETIQUETAS
sct_due_date=FE_VENCIMIENTO
sct_sla_due=FE_VENCIMIENTO_SLA
sct_work_end=FE_FINALIZACION_REAL
sct_u_previous_assignment_group=TE_GRUPO_ASIGNADO_PREVIO
sct_assignment_group=TE_GRUPO_ASIGNACION
taskslatable_end_time=FE_HORA_FINALIZACION
taskslatable_planned_end_time=FE_HORA_INFRACCION
taskslatable_start_time=FE_HORA_INICIO
sct_impact=TE_IMPACTO
sct_expected_start=FE_INICIO_ESPERADO
sct_work_start=FE_INICIO_REAL
sct_close_notes=TE_NOTAS_CIERRE
sct_work_notes=TE_NOTAS_TRABAJO
sct_reassignment_count=NU_REASIGNACION
sct_task_effective_number=CA_NUMERO_EFECTIVO
sct_comments=TE_OBSERVACIONES_ADICIONALES
sct_order=TE_ORDEN
taskslatable_business_percentage=NU_PCJE_NEGOCIO_TRANSCURRIDO
taskslatable_percentage=NU_PCJE_REAL_TRANSCURRIDO
sct_parent=CA_PRINCIPAL
sct_priority=TE_PRIORIDAD
taskslatable_u_assignment_group=TE_SLA_GRUPO_ASIGNACION
sct_request=CA_SOLICITUD
taskslatable_task=CA_TAREA
taskslatable_business_time_left=NU_TIEMPO_NEGOCIO_RESTANTE
taskslatable_pause_time=NU_TIEMPO_PAUSA
sct_calendar_stc=NU_TIEMPO_RESOLUCION
taskslatable_original_breach_time=FE_TIEMPO_ORIGINAL_INC
taskslatable_time_left=NU_TIEMPO_RESTANTE_REAL
sct_time_worked=NU_TIEMPO_TRABAJADO
sct_u_creation_type=TE_TIPO_CREACION
sct_urgency=TE_URGENCIA
sct_activity_due=FE_VENCIMIENTO_ACTIVIDAD