number=CA_CODIGO
assignment_group=TE_GRUPO_ASIGNACION
closed_at=FE_CERRADO
variables.18d673ba47eb86907b37945e036d43d2=NU_HORAS_EST_TOT_EJECUCION
variables.e02f86f14795b6107b37945e036d4386=NU_HORAS_FACTORIA